name: better_io
description: "A Flutter-based productivity and self-growth hub combining task management,
 habit tracking, and a customizable personal library into one intuitive app."
publish_to: 'none'

version: 1.0.0+1

homepage: https://github.com/AlexeyFloppa/better_io
repository: https://github.com/AlexeyFloppa/better_io
issue_tracker: https://github.com/AlexeyFloppa/better_io/issues

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  syncfusion_flutter_calendar: ^29.1.38
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  provider: ^6.1.5
  intl: ^0.20.2
  flutter_colorpicker: ^1.1.0
  rrule: ^0.2.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  hive_generator: ^1.1.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/logos/app_logo.png"